# Generated by Django 5.1 on 2024-08-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockRank',
            fields=[
                ('country', models.CharField(db_column='country', max_length=255)),
                ('ticker', models.CharField(db_column='ticker', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('percent', models.FloatField(db_column='percent')),
                ('rank', models.IntegerField(db_column='rank')),
            ],
            options={
                'db_table': 'stock_rank',
                'managed': False,
            },
        ),
    ]
