# Generated by Django 5.1 on 2024-08-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KRSTOCKDATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=50)),
                ('open_value', models.DecimalField(db_column='open_value', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'kr_stock_data',
            },
        ),
        migrations.CreateModel(
            name='KRTOP100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(db_column='date')),
                ('Name', models.CharField(db_column='name', max_length=100)),
                ('Code', models.CharField(db_column='code', max_length=100)),
            ],
            options={
                'db_table': 'kr_top100',
            },
        ),
        migrations.CreateModel(
            name='USSTOCKDATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=50)),
                ('open_value', models.DecimalField(db_column='open_value', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'us_stock_data',
            },
        ),
        migrations.CreateModel(
            name='USTOP100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(db_column='name', max_length=100)),
                ('Code', models.CharField(db_column='code', max_length=100)),
                ('excode', models.CharField(db_column='excode', max_length=100)),
            ],
            options={
                'db_table': 'ustop100',
            },
        ),
    ]
