# Generated by Django 5.1 on 2024-08-15 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('yen_100', models.CharField(db_column='100엔', max_length=50)),
                ('dollar', models.CharField(db_column='달러', max_length=50)),
                ('yuan', models.CharField(db_column='위안', max_length=50)),
            ],
            options={
                'db_table': 'exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('kospi', models.CharField(db_column='kospi지수', max_length=50)),
                ('kosdaq', models.CharField(db_column='kosdaq지수', max_length=50)),
                ('volume', models.CharField(db_column='거래량_코스닥시장', max_length=50)),
                ('amount', models.CharField(db_column='거래대금_코스닥시장', max_length=50)),
            ],
            options={
                'db_table': 'kospi',
            },
        ),
        migrations.CreateModel(
            name='newssentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('sentiment', models.CharField(db_column='newssentiment', max_length=50)),
            ],
            options={
                'db_table': 'newssentiment',
            },
        ),
    ]
