# Generated by Django 5.1 on 2024-08-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('yen_100', models.CharField(db_column='100엔', max_length=50)),
                ('dollar', models.CharField(db_column='달러', max_length=50)),
                ('yuan', models.CharField(db_column='위안', max_length=50)),
            ],
            options={
                'db_table': 'exchange_rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('date', models.DateField(db_column='date')),
                ('change', models.DecimalField(db_column='change', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'high_volatility_kr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HighUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('date', models.DateField(db_column='date')),
                ('change', models.DecimalField(db_column='change', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'high_volatility_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='time', max_length=50)),
                ('koribor_12m', models.CharField(db_column='koribor(12개월)', max_length=50)),
                ('treasury_10y', models.CharField(db_column='국고채(10년)', max_length=50)),
                ('treasury_2y', models.CharField(db_column='국고채(2년)', max_length=50)),
                ('treasury_5y', models.CharField(db_column='국고채(5년)', max_length=50)),
                ('call_rate_bank_securities', models.CharField(db_column='콜금리(1일, 은행증권금융차입)', max_length=50)),
                ('call_rate_total', models.CharField(db_column='콜금리(1일, 전체거래)', max_length=50)),
                ('call_rate_broker_deal', models.CharField(db_column='콜금리(1일, 중개회사거래)', max_length=50)),
                ('corporate_bond_aa', models.CharField(db_column='회사채(3년, aa-)', max_length=50)),
                ('corporate_bond_bbb', models.CharField(db_column='회사채(3년, bbb-)', max_length=50)),
            ],
            options={
                'db_table': 'market_interest_rates',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kospi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('kospi', models.CharField(db_column='kospi지수', max_length=50)),
                ('kosdaq', models.CharField(db_column='kosdaq지수', max_length=50)),
                ('volume', models.CharField(db_column='거래량_코스닥시장', max_length=50)),
                ('amount', models.CharField(db_column='거래대금_코스닥시장', max_length=50)),
            ],
            options={
                'db_table': 'kospi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='newssentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(db_column='TIME', max_length=50)),
                ('sentiment', models.CharField(db_column='newssentiment', max_length=50)),
            ],
            options={
                'db_table': 'newssentiment',
                'managed': False,
            },
        ),
    ]
