# Generated by Django 5.1 on 2024-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKRTop100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('name', models.CharField(db_column='name')),
                ('code', models.CharField(db_column='code')),
            ],
            options={
                'db_table': 'kr_top100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockUSTop100',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name')),
                ('code', models.CharField(db_column='code')),
                ('excode', models.CharField(db_column='excode')),
            ],
            options={
                'db_table': 'us_top100',
                'managed': False,
            },
        ),
    ]
