# Generated by Django 5.1 on 2024-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0002_stockkrtop100_stockustop100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockustop100',
            table='ustop100',
        ),
    ]
