# Generated by Django 5.1 on 2024-08-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newb', '0003_alter_stockustop100_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockKRHistory',
            fields=[
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=20)),
                ('open_value', models.DecimalField(db_column='open_value', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'kr_stock_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockUSHistory',
            fields=[
                ('date', models.DateField(db_column='date', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('code', models.CharField(db_column='code', max_length=20)),
                ('open_value', models.DecimalField(db_column='open_value', decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'us_stock_data',
                'managed': False,
            },
        ),
    ]
