name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때마다 워크플로우가 실행됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'

    - name: Create .ssh directory
      run: mkdir -p ~/.ssh

    - name: Add Bastion SSH key
      run: |
        echo "${{ secrets.BASTION_SSH_KEY }}" > ~/.ssh/bastion_key.pem
        chmod 600 ~/.ssh/bastion_key.pem

    - name: Add Server SSH key
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/server_key.pem
        chmod 600 ~/.ssh/server_key.pem

    - name: Deploy to Private Server via Bastion Host
      run: |
        ssh -T -i ~/.ssh/bastion_key.pem -o StrictHostKeyChecking=no -J ${{ secrets.BASTION_USER }}@${{ secrets.BASTION_HOST }} -o "UserKnownHostsFile=/dev/null" -o "LogLevel=ERROR" -i ~/.ssh/server_key.pem ${{ secrets.SSH_USER }}@${{ secrets.PRIVATE_HOST }} << 'EOF'
        cd /home/ubuntu/NewbStock_Server
        git pull origin main
        source /home/ubuntu/NewbStock_Server/venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        python manage.py collectstatic --noinput
        systemctl restart gunicorn
        EOF
