name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check SSH Key
      env:
        BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "Bastion SSH Key starts with: ${BASTION_SSH_KEY:0:10}"
        echo "Server SSH Key starts with: ${SERVER_SSH_KEY:0:10}"

    - name: Deploy to server through Bastion Host
      env:
        BASTION_HOST: ${{ secrets.BASTION_HOST }}
        BASTION_USER: ${{ secrets.BASTION_USER }}
        BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        # Bastion SSH 키를 임시 파일로 저장
        echo "${BASTION_SSH_KEY}" > bastion_key.pem
        chmod 600 bastion_key.pem

        # 서버 SSH 키를 임시 파일로 저장
        echo "${SERVER_SSH_KEY}" > server_key.pem
        chmod 600 server_key.pem
        
        ssh -i bastion_key.pem -o "ProxyCommand=ssh -i bastion_key.pem -W %h:%p ${BASTION_USER}@${BASTION_HOST}" -i server_key.pem ${SERVER_USER}@${SERVER_HOST} << 'EOF'
        cd /home/ubuntu/NewbStock_Server
        git pull origin main
        source /home/ubuntu/NewbStock_Server/venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
