name: Django CI/CD

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로우가 실행됨

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.3'  # 원하는 Python 버전 지정

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        HOST: ${{ secrets.DEPLOY_HOST }}
        USER: ${{ secrets.DEPLOY_USER }}
        KEY: ${{ secrets.DEPLOY_KEY }}
        PROJECT_DIR: ${{ secrets.DEPLOY_PROJECT_DIR }}
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 600 deploy_key.pem
        ssh -i deploy_key.pem -o StrictHostKeyChecking=no -t ${{ env.USER }}@${{ env.HOST }} << EOF
          cd ${{ env.PROJECT_DIR }}
          git pull origin main
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        EOF
    