name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server through Bastion Host
      env:
        BASTION_HOST: ${{ secrets.BASTION_HOST }}
        BASTION_USER: ${{ secrets.BASTION_USER }}
        BASTION_SSH_KEY: ${{ secrets.BASTION_SSH_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        ssh -i $BASTION_SSH_KEY -o "ProxyCommand=ssh -i $BASTION_SSH_KEY -W %h:%p $BASTION_USER@$BASTION_HOST" $SERVER_USER@$SERVER_HOST << 'EOF'
        cd /home/ubuntu/NewbStock_Server
        git pull origin main
        source /home/ubuntu/NewbStock_Server/venv/bin/activate
        pip install -r requirements.txt
        python manage.py migrate
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx
        EOF
