name: Deploy Django Application

on:
  push:
    branches:
      - main  # 자동 배포를 원하는 브랜치

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            # Navigate to application directory
            cd /path/to/your/app

            # Pull the latest code from the repository
            git pull origin main

            # Activate the virtual environment
            source venv/bin/activate

            # Install/update dependencies
            pip install -r requirements.txt

            # Run database migrations
            python manage.py migrate

            # Collect static files
            python manage.py collectstatic --noinput

            # Restart Gunicorn to apply the changes
            sudo systemctl restart gunicorn

            # Restart Nginx to apply any configuration changes (optional)
            sudo systemctl restart nginx
          EOF
